CI: Add pre-commit linters, autoformatters (#299)
* Add pre-commit linters, formatters

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>

* add descriptive name for fail msg step

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>

* shorten precommit makefile cmd

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>

* make fix_format

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>

* autoformat all lint errs

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>

* backtick quote to avoid formatter

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>

* add shfmt for bash linting

Signed-off-by: Yuki Sawa <yukisawa@gmail.com>
Signed-off-by: Debby Ku <debbyku.2008@gmail.com>

diff --git a/.github/workflows/pullrequest.yaml b/.github/workflows/pullrequest.yaml
--- a/.github/workflows/pullrequest.yaml
+++ b/.github/workflows/pullrequest.yaml
@@ -6,10 +6,13 @@ on:
 jobs:
   check:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v2
+
       - name: check format
         run: make check_format
+
   build:
     runs-on: ubuntu-latest
 
@@ -17,5 +20,30 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: build and test
+        run: make docker_tests
+
+  precommits:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: actions/setup-python@v2
+        with:
+          python-version: "3.9"
+
+      - uses: actions/setup-go@v2
+        with:
+          go-version: "1.16"
+
+      - name: run pre-commits
         run: |
-          make docker_tests
+          make precommit_install
+          pre-commit run -a
+
+      # If previous stage fails, print resolution steps
+      - if: ${{ failure() }}
+        name: Read for resolution steps
+        run: |
+          echo "Pre-commits failed! Run 'make precommit_install' then 'pre-commits run -a' to fix."
+          exit 1
